In [30]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/home/bjoern_local/miniforge3/envs/pypsa-eur/lib/python3.12/site-packages', '/home/bjoern_local/git/pypsa-eur-evt/rules/MA', '/home/bjoern_local/.cache/snakemake/snakemake/source-cache/runtime-cache/tmp2fsxtb_l/file/home/bjoern_local/git/pypsa-eur-evt/rules/../scripts', '/home/bjoern_local/git/pypsa-eur-evt/rules', '/home/bjoern_local/git/pypsa-eur-evt', '/home/bjoern_local/miniforge3/envs/pypsa-eur/bin', '/home/bjoern_local/miniforge3/envs/pypsa-eur/lib/python3.12', '/home/bjoern_local/miniforge3/envs/pypsa-eur/lib/python3.12/lib-dynload', '/home/bjoern_local/miniforge3/envs/pypsa-eur/lib/python3.12/site-packages', '/home/bjoern_local/git/pypsa-eur-evt/rules/MA/notebooks']);import pickle;from snakemake import script;script.snakemake = pickle.loads(b'\x80\x04\x95\x1b\x83\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c#data/MA/loads/NIP2030/Nachfrage.csv\x94\x8c\x1cdata/MA/loads/NIP2030/PV.csv\x94\x8c\x1edata/MA/loads/NIP2030/Wind.csv\x94\x8c"data/MA/loads/NIP2030/biomasse.csv\x94\x8c*data/MA/loads/NIP2030/GrossWasserkraft.csv\x94\x8c*data/MA/loads/NIP2030/Kleinwasserkraft.csv\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\tnachfrage\x94K\x00N\x86\x94\x8c\x02pv\x94K\x01N\x86\x94\x8c\x04wind\x94K\x02N\x86\x94\x8c\x08biomasse\x94K\x03N\x86\x94\x8c\x11gross_wasserkraft\x94K\x04N\x86\x94\x8c\x11klein_wasserkraft\x94K\x05N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh!h\x06\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h!sbh"h$)\x81\x94}\x94h\'h"sbh\x13h\nh\x15h\x0bh\x17h\x0ch\x19h\rh\x1bh\x0eh\x1dh\x0fub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8c(residual/NIP2030/residual_inputs.parquet\x94a}\x94(h\x11}\x94h\x1f]\x94(h!h"eh!h$)\x81\x94}\x94h\'h!sbh"h$)\x81\x94}\x94h\'h"sbub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(\x8c\x08scenario\x94\x8c\x07NIP2030\x94\x8c\tinput_dir\x94\x8c\rdata/MA/loads\x94\x8c\x06inputs\x94}\x94(\x8c\tnachfrage\x94\x8c${input_dir}/{scenario}/Nachfrage.csv\x94\x8c\x02pv\x94\x8c\x1d{input_dir}/{scenario}/PV.csv\x94\x8c\x04wind\x94\x8c\x1f{input_dir}/{scenario}/Wind.csv\x94\x8c\x08biomasse\x94\x8c#{input_dir}/{scenario}/biomasse.csv\x94\x8c\x11gross_wasserkraft\x94\x8c+{input_dir}/{scenario}/GrossWasserkraft.csv\x94\x8c\x11klein_wasserkraft\x94\x8c+{input_dir}/{scenario}/Kleinwasserkraft.csv\x94uua}\x94(h\x11}\x94\x8c\x06config\x94K\x00N\x86\x94sh\x1f]\x94(h!h"eh!h$)\x81\x94}\x94h\'h!sbh"h$)\x81\x94}\x94h\'h"sbhOh:ub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94}\x94(h\x11}\x94h\x1f]\x94(h!h"eh!h$)\x81\x94}\x94h\'h!sbh"h$)\x81\x94}\x94h\'h"sbub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x04/tmp\x94e}\x94(h\x11}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x1f]\x94(h!h"eh!h$)\x81\x94}\x94h\'h!sbh"h$)\x81\x94}\x94h\'h"sbhiK\x01hkK\x01hmhfub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94}\x94(h\x11}\x94h\x1f]\x94(h!h"eh!h$)\x81\x94}\x94h\'h!sbh"h$)\x81\x94}\x94h\'h"sbubhO}\x94(\x8c\x03run\x94}\x94(\x8c\x04name\x94\x8c\x11128_wAT_entsoe_MA\x94\x8c\x13disable_progressbar\x94\x89\x8c\x10shared_resources\x94}\x94(\x8c\x06policy\x94\x88\x8c\x07exclude\x94]\x94u\x8c\x0eshared_cutouts\x94\x88\x8c\x06prefix\x94\x8c\x00\x94\x8c\tscenarios\x94}\x94(\x8c\x06enable\x94\x89\x8c\x04file\x94\x8c\x15config/scenarios.yaml\x94u\x8c\x14use_shadow_directory\x94\x88u\x8c\x08scenario\x94}\x94(\x8c\x05simpl\x94]\x94h\x8ca\x8c\x02ll\x94]\x94\x8c\x04vopt\x94a\x8c\x08clusters\x94]\x94K\x80a\x8c\x04opts\x94]\x94h\x8ca\x8c\x0bsector_opts\x94]\x94h\x8ca\x8c\x11planning_horizons\x94]\x94h\x8cau\x8c\tcountries\x94]\x94(\x8c\x02AL\x94\x8c\x02AT\x94\x8c\x02BA\x94\x8c\x02BE\x94\x8c\x02BG\x94\x8c\x02CH\x94\x8c\x02CZ\x94\x8c\x02DE\x94\x8c\x02DK\x94\x8c\x02EE\x94\x8c\x02ES\x94\x8c\x02FI\x94\x8c\x02FR\x94\x8c\x02GB\x94\x8c\x02GR\x94\x8c\x02HR\x94\x8c\x02HU\x94\x8c\x02IE\x94\x8c\x02IT\x94\x8c\x02LT\x94\x8c\x02LU\x94\x8c\x02LV\x94\x8c\x02ME\x94\x8c\x02MD\x94\x8c\x02MK\x94\x8c\x02NL\x94\x8c\x02NO\x94\x8c\x02PL\x94\x8c\x02PT\x94\x8c\x02RO\x94\x8c\x02RS\x94\x8c\x02SE\x94\x8c\x02SI\x94\x8c\x02SK\x94\x8c\x02UA\x94e\x8c\x0belectricity\x94}\x94(\x8c\x12custom_powerplants\x94\x88\x8c\x08co2limit\x94GA\x96\xddE\x80\x00\x00\x00\x8c\x07co2base\x94GA\xdc\x94\x96\xe0\x00\x00\x00\x8c\x08voltages\x94]\x94(G@k\x80\x00\x00\x00\x00\x00G@r\xc0\x00\x00\x00\x00\x00G@t\xa0\x00\x00\x00\x00\x00G@w\xc0\x00\x00\x00\x00\x00G@y\x00\x00\x00\x00\x00\x00G@\x7f@\x00\x00\x00\x00\x00G@\x87p\x00\x00\x00\x00\x00e\x8c\x0cbase_network\x94\x8c\x0cosm-prebuilt\x94\x8c\x14osm-prebuilt-version\x94G?\xe3333333\x8c\x0fgaslimit_enable\x94\x89\x8c\x08gaslimit\x94\x89\x8c\x0fco2limit_enable\x94\x89\x8c\x13operational_reserve\x94}\x94(\x8c\x08activate\x94\x89\x8c\x0cepsilon_load\x94G?\x94z\xe1G\xae\x14{\x8c\x0cepsilon_vres\x94G?\x94z\xe1G\xae\x14{\x8c\x0bcontingency\x94M\xa0\x0fu\x8c\tmax_hours\x94}\x94(\x8c\x07battery\x94K\x06\x8c\x02H2\x94K\xa8u\x8c\x13extendable_carriers\x94}\x94(\x8c\tGenerator\x94]\x94(\x8c\x05solar\x94\x8c\nsolar-hsat\x94\x8c\x06onwind\x94\x8c\noffwind-ac\x94\x8c\noffwind-dc\x94\x8c\roffwind-float\x94\x8c\x04OCGT\x94\x8c\x04CCGT\x94e\x8c\x0bStorageUnit\x94]\x94\x8c\x05Store\x94]\x94(\x8c\x07battery\x94\x8c\x02H2\x94e\x8c\x04Link\x94]\x94u\x8c\x12powerplants_filter\x94\x8c`(DateOut >= 2024 or DateOut != DateOut) and not (Country == \'Germany\' and Fueltype == \'Nuclear\')\x94\x8c\x16everywhere_powerplants\x94]\x94\x8c\x15conventional_carriers\x94]\x94(\x8c\x07nuclear\x94\x8c\x03oil\x94\x8c\x04OCGT\x94\x8c\x04CCGT\x94\x8c\x04coal\x94\x8c\x07lignite\x94\x8c\ngeothermal\x94\x8c\x07biomass\x94e\x8c\x12renewable_carriers\x94]\x94(\x8c\x05solar\x94\x8c\nsolar-hsat\x94\x8c\x06onwind\x94\x8c\noffwind-ac\x94\x8c\noffwind-dc\x94\x8c\roffwind-float\x94\x8c\x05hydro\x94e\x8c\x1destimate_renewable_capacities\x94}\x94(\x8c\x06enable\x94\x88\x8c\tfrom_opsd\x94\x88\x8c\x04year\x94M\xe4\x07\x8c\x0fexpansion_limit\x94\x89\x8c\x12technology_mapping\x94}\x94(\x8c\x08Offshore\x94]\x94(\x8c\noffwind-ac\x94\x8c\noffwind-dc\x94\x8c\roffwind-float\x94e\x8c\x07Onshore\x94]\x94\x8c\x06onwind\x94a\x8c\x02PV\x94]\x94\x8c\x05solar\x94auu\x8c\x07autarky\x94}\x94(\x8c\x06enable\x94\x89\x8c\nby_country\x94\x89u\x8c\x12transmission_limit\x94\x8c\x04vopt\x94u\x8c\x05lines\x94}\x94(\x8c\x10reconnect_crimea\x94\x89\x8c\x12under_construction\x94\x8c\x06remove\x94\x8c\x05types\x94}\x94(G@k\x80\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 2-bundle 220.0\x94G@r\xc0\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 3-bundle 300.0\x94G@t\xa0\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 3-bundle 300.0\x94G@w\xc0\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 4-bundle 380.0\x94G@y\x00\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 4-bundle 380.0\x94G@\x7f@\x00\x00\x00\x00\x00\x8c\x1bAl/St 240/40 4-bundle 380.0\x94G@\x87p\x00\x00\x00\x00\x00\x8c\x1bAl/St 560/50 4-bundle 750.0\x94u\x8c\x08s_max_pu\x94G?\xe6ffffff\x8c\ts_nom_max\x94G\x7f\xf0\x00\x00\x00\x00\x00\x00\x8c\rmax_extension\x94M N\x8c\rlength_factor\x94G?\xf4\x00\x00\x00\x00\x00\x00\x8c\x13dynamic_line_rating\x94}\x94(\x8c\x08activate\x94\x89\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x11correction_factor\x94G?\xeeffffff\x8c\x16max_voltage_difference\x94\x89\x8c\x0fmax_line_rating\x94\x89uu\x8c\x05links\x94}\x94(\x8c\x12under_construction\x94\x8c\x06remove\x94\x8c\x08p_max_pu\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\tp_nom_max\x94G\x7f\xf0\x00\x00\x00\x00\x00\x00\x8c\rmax_extension\x94M0u\x8c\rlength_factor\x94G?\xf4\x00\x00\x00\x00\x00\x00u\x8c\x15transmission_projects\x94}\x94(\x8c\x06enable\x94\x88\x8c\x07include\x94}\x94(\x8c\ttyndp2020\x94\x89\x8c\x03nep\x94\x89\x8c\x06manual\x94\x89u\x8c\x04skip\x94]\x94(\x8c\x0eupgraded_lines\x94\x8c\x0eupgraded_links\x94e\x8c\x06status\x94]\x94(\x8c\x12under_construction\x94\x8c\rin_permitting\x94\x8c\tconfirmed\x94e\x8c\x11new_link_capacity\x94\x8c\x04zero\x94u\x8c\x06enable\x94}\x94(\x8c\x08retrieve\x94\x88\x8c\x13retrieve_databundle\x94\x88\x8c\x12retrieve_cost_data\x94\x88\x8c\x0fretrieve_cutout\x94\x88\x8c\x0cbuild_cutout\x94\x89\x8c\rdrop_leap_day\x94\x88u\x8c\nclustering\x94}\x94(\x8c\rfocus_weights\x94}\x94\x8c\x02AT\x94G?\xd9\x99\x99\x99\x99\x99\x9as\x8c\x10simplify_network\x94}\x94(\x8c\x0eto_substations\x94\x89\x8c\x1bremove_stubs_across_borders\x94\x88\x8c\x0cremove_stubs\x94\x88u\x8c\x0fcluster_network\x94}\x94(\x8c\talgorithm\x94\x8c\x06kmeans\x94\x8c\x0chac_features\x94]\x94(\x8c\x07wnd100m\x94\x8c\rinflux_direct\x94eu\x8c\x08temporal\x94}\x94(\x8c\x0fresolution_elec\x94\x8c\x026H\x94\x8c\x11resolution_sector\x94\x89u\x8c\x04mode\x94\x8c\x06busmap\x94\x8c\x0eadministrative\x94}\x94\x8c\x05level\x94K\x01s\x8c\x10exclude_carriers\x94]\x94\x8c\x1bconsider_efficiency_classes\x94\x89\x8c\x16aggregation_strategies\x94}\x94\x8c\ngenerators\x94}\x94(\x8c\x0bcommittable\x94\x8c\x03any\x94\x8c\rramp_limit_up\x94\x8c\x03max\x94\x8c\x0framp_limit_down\x94\x8c\x03max\x94usu\x8c\x07solving\x94}\x94(\x8c\x06solver\x94}\x94(\x8c\x04name\x94\x8c\x06gurobi\x94\x8c\x07options\x94\x8c\x16gurobi-default-threads\x94u\x8c\x0esolver_options\x94}\x94(\x8c\x16gurobi-default-threads\x94}\x94(\x8c\x07threads\x94K\x14\x8c\x06method\x94K\x02\x8c\tcrossover\x94K\x00\x8c\nBarConvTol\x94G>\xb0\xc6\xf7\xa0\xb5\xed\x8d\x8c\x04Seed\x94K{\x8c\x07AggFill\x94K\x00\x8c\x07PreDual\x94K\x00\x8c\x17GURO_PAR_BARDENSETHRESH\x94K\xc8u\x8c\rcplex-default\x94}\x94(\x8c\x07threads\x94K\x04\x8c\x08lpmethod\x94K\x04\x8c\x0csolutiontype\x94K\x02\x8c\x13barrier.convergetol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\x11feasopt.tolerance\x94G>\xb0\xc6\xf7\xa0\xb5\xed\x8du\x8c\x0ccopt-default\x94}\x94(\x8c\x07Threads\x94K\x08\x8c\x08LpMethod\x94K\x02\x8c\tCrossover\x94K\x00\x8c\x06RelGap\x94G>\xb0\xc6\xf7\xa0\xb5\xed\x8d\x8c\x07Dualize\x94K\x00u\x8c\x08copt-gpu\x94}\x94(\x8c\x08LpMethod\x94K\x06\x8c\x07GPUMode\x94K\x01\x8c\x07PDLPTol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\tCrossover\x94K\x00u\x8c\x0bcbc-default\x94}\x94\x8c\x0cglpk-default\x94}\x94\x8c\rhighs-default\x94}\x94(\x8c\x07threads\x94K\x01\x8c\x06solver\x94\x8c\x03ipm\x94\x8c\rrun_crossover\x94\x8c\x03off\x94\x8c\x12small_matrix_value\x94\x8c\x041e-6\x94\x8c\x12large_matrix_value\x94\x8c\x031e9\x94\x8c\x1cprimal_feasibility_tolerance\x94\x8c\x041e-5\x94\x8c\x1adual_feasibility_tolerance\x94\x8c\x041e-5\x94\x8c\x18ipm_optimality_tolerance\x94\x8c\x041e-4\x94\x8c\x08parallel\x94\x8c\x02on\x94\x8c\x0brandom_seed\x94K{u\x8c\rhighs-simplex\x94}\x94(\x8c\x06solver\x94\x8c\x07simplex\x94\x8c\x08parallel\x94\x8c\x02on\x94\x8c\x1cprimal_feasibility_tolerance\x94\x8c\x041e-5\x94\x8c\x1adual_feasibility_tolerance\x94\x8c\x041e-5\x94\x8c\x0brandom_seed\x94K{u\x8c\x0egurobi-default\x94}\x94(\x8c\x07threads\x94K\x08\x8c\x06method\x94K\x02\x8c\tcrossover\x94K\x00\x8c\nBarConvTol\x94G>\xb0\xc6\xf7\xa0\xb5\xed\x8d\x8c\x04Seed\x94K{\x8c\x07AggFill\x94K\x00\x8c\x07PreDual\x94K\x00\x8c\x17GURO_PAR_BARDENSETHRESH\x94K\xc8u\x8c\x14gurobi-numeric-focus\x94}\x94(\x8c\x0cNumericFocus\x94K\x03\x8c\x06method\x94K\x02\x8c\tcrossover\x94K\x00\x8c\x0eBarHomogeneous\x94K\x01\x8c\nBarConvTol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\x0eFeasibilityTol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\rOptimalityTol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x08ObjScale\x94G\xbf\xe0\x00\x00\x00\x00\x00\x00\x8c\x07threads\x94K\x08\x8c\x04Seed\x94K{u\x8c\x0fgurobi-fallback\x94}\x94(\x8c\tcrossover\x94K\x00\x8c\x06method\x94K\x02\x8c\x0eBarHomogeneous\x94K\x01\x8c\nBarConvTol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\x0eFeasibilityTol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\rOptimalityTol\x94G>\xe4\xf8\xb5\x88\xe3h\xf1\x8c\x04Seed\x94K{\x8c\x07threads\x94K\x08uu\x8c\x06mem_mb\x94M0u\x8c\x18memory_logging_frequency\x94K\x1e\x8c\x07runtime\x94\x8c\x026h\x94\x8c\x07options\x94}\x94(\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{\x8c\rload_shedding\x94\x89\x8c\x10curtailment_mode\x94\x89\x8c\x0bnoisy_costs\x94\x88\x8c\x0fskip_iterations\x94\x88\x8c\x0frolling_horizon\x94\x89\x8c\x04seed\x94K{\x8c\x1acustom_extra_functionality\x94\x8c%../data/custom_extra_functionality.py\x94\x8c\x10track_iterations\x94\x89\x8c\x0emin_iterations\x94K\x02\x8c\x0emax_iterations\x94K\x03\x8c\x13transmission_losses\x94K\x02\x8c\x1alinearized_unit_commitment\x94\x88\x8c\x07horizon\x94Mm\x01\x8c\x13post_discretization\x94}\x94(\x8c\x06enable\x94\x89\x8c\x0eline_unit_size\x94M\xa4\x06\x8c\x0eline_threshold\x94G?\xd3333333\x8c\x0elink_unit_size\x94}\x94(\x8c\x02DC\x94M\xd0\x07\x8c\x0bH2 pipeline\x94M\xb0\x04\x8c\x0cgas pipeline\x94M\xdc\x05u\x8c\x0elink_threshold\x94}\x94(\x8c\x02DC\x94G?\xd3333333\x8c\x0bH2 pipeline\x94G?\xd3333333\x8c\x0cgas pipeline\x94G?\xd3333333u\x8c\x19fractional_last_unit_size\x94\x89uu\x8c\x10agg_p_nom_limits\x94}\x94(\x8c\x0bagg_offwind\x94\x89\x8c\x10include_existing\x94\x89\x8c\x04file\x94\x8c\x19data/agg_p_nom_minmax.csv\x94u\x8c\x0bconstraints\x94}\x94(\x8c\x03CCL\x94\x89\x8c\x02EQ\x94\x89\x8c\x03BAU\x94\x89\x8c\x04SAFE\x94\x89u\x8c\x0fcheck_objective\x94}\x94(\x8c\x06enable\x94\x89\x8c\x0eexpected_value\x94\x8c\x04None\x94\x8c\x04atol\x94J@B\x0f\x00\x8c\x04rtol\x94G?\x84z\xe1G\xae\x14{uu\x8c\x12austria_shapefiles\x94}\x94(\x8c\x05buses\x94\x8c\x1ddata/shapefiles/buses_aut.shp\x94\x8c\x05lines\x94\x8c\x1ddata/shapefiles/lines_aut.shp\x94u\x8c\x0eoutput_network\x94\x8c\x1dresources/networks/austria.nc\x94\x8c\x04case\x94\x8c\x02MA\x94\x8c\x0eresidual_loads\x94h:\x8c\x07version\x94\x8c\nv2025.01.0\x94\x8c\x08tutorial\x94\x89\x8c\x07logging\x94}\x94(\x8c\x05level\x94\x8c\x04INFO\x94\x8c\x06format\x94\x8c"%(levelname)s:%(name)s:%(message)s\x94u\x8c\x06remote\x94}\x94(\x8c\x03ssh\x94h\x8c\x8c\x04path\x94h\x8cu\x8c\tforesight\x94\x8c\tovernight\x94\x8c\tsnapshots\x94}\x94(\x8c\x05start\x94\x8c\n2013-01-01\x94\x8c\x03end\x94\x8c\n2014-01-01\x94\x8c\tinclusive\x94\x8c\x04left\x94u\x8c\nco2_budget\x94}\x94(M\xe4\x07G?\xe7\n=p\xa3\xd7\nM\xe9\x07G?\xe4\xbcj~\xf9\xdb#M\xee\x07G?\xdc\xcc\xcc\xcc\xcc\xcc\xcdM\xf3\x07G?\xd0\x00\x00\x00\x00\x00\x00M\xf8\x07G?\xb9\x99\x99\x99\x99\x99\x9aM\xfd\x07G?\xa9\x99\x99\x99\x99\x99\x9aM\x02\x08G\x00\x00\x00\x00\x00\x00\x00\x00u\x8c\x06atlite\x94}\x94(\x8c\x10cutout_directory\x94\x8c\x07cutouts\x94\x8c\x0edefault_cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\nnprocesses\x94K\x04\x8c\rshow_progress\x94\x89\x8c\x07cutouts\x94}\x94\x8c\x17europe-2013-sarah3-era5\x94}\x94(\x8c\x06module\x94]\x94(\x8c\x05sarah\x94\x8c\x04era5\x94e\x8c\x01x\x94]\x94(G\xc0(\x00\x00\x00\x00\x00\x00G@E\x00\x00\x00\x00\x00\x00e\x8c\x01y\x94]\x94(G@@\x80\x00\x00\x00\x00\x00G@R\x00\x00\x00\x00\x00\x00e\x8c\x02dx\x94G?\xd3333333\x8c\x02dy\x94G?\xd3333333\x8c\x04time\x94]\x94(\x8c\x042013\x94\x8c\x042013\x94eusu\x8c\trenewable\x94}\x94(\x8c\x06onwind\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x04wind\x94\x8c\x07turbine\x94\x8c\x0fVestas_V112_3MW\x94\x8c\x06smooth\x94\x89\x8c\x14add_cutout_windspeed\x94\x88u\x8c\x11capacity_per_sqkm\x94K\x03\x8c\x06corine\x94}\x94(\x8c\ngrid_codes\x94]\x94(K\x0cK\rK\x0eK\x0fK\x10K\x11K\x12K\x13K\x14K\x15K\x16K\x17K\x18K\x19K\x1aK\x1bK\x1cK\x1dK\x1fK e\x8c\x08distance\x94M\xe8\x03\x8c\x13distance_grid_codes\x94]\x94(K\x01K\x02K\x03K\x04K\x05K\x06eu\x8c\x05luisa\x94\x89\x8c\x06natura\x94\x88\x8c\x13excluder_resolution\x94Kd\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{u\x8c\noffwind-ac\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x04wind\x94\x8c\x07turbine\x94\x8c#NREL_ReferenceTurbine_2020ATB_5.5MW\x94\x8c\x06smooth\x94\x89\x8c\x14add_cutout_windspeed\x94\x88u\x8c\x11capacity_per_sqkm\x94K\x02\x8c\x11correction_factor\x94G?\xecV\x04\x18\x93t\xbc\x8c\x06corine\x94]\x94(K,K\xffe\x8c\x05luisa\x94\x89\x8c\x06natura\x94\x88\x8c\x0eship_threshold\x94M\x90\x01\x8c\tmax_depth\x94K<\x8c\x12max_shore_distance\x94M0u\x8c\x13excluder_resolution\x94K\xc8\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{\x8c\x0flandfall_length\x94K\nu\x8c\noffwind-dc\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x04wind\x94\x8c\x07turbine\x94\x8c#NREL_ReferenceTurbine_2020ATB_5.5MW\x94\x8c\x06smooth\x94\x89\x8c\x14add_cutout_windspeed\x94\x88u\x8c\x11capacity_per_sqkm\x94K\x02\x8c\x11correction_factor\x94G?\xecV\x04\x18\x93t\xbc\x8c\x06corine\x94]\x94(K,K\xffe\x8c\x05luisa\x94\x89\x8c\x06natura\x94\x88\x8c\x0eship_threshold\x94M\x90\x01\x8c\tmax_depth\x94K<\x8c\x12min_shore_distance\x94M0u\x8c\x13excluder_resolution\x94K\xc8\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{\x8c\x0flandfall_length\x94K\nu\x8c\roffwind-float\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x04wind\x94\x8c\x07turbine\x94\x8c"NREL_ReferenceTurbine_5MW_offshore\x94\x8c\x06smooth\x94\x89\x8c\x14add_cutout_windspeed\x94\x88u\x8c\x11capacity_per_sqkm\x94K\x02\x8c\x11correction_factor\x94G?\xecV\x04\x18\x93t\xbc\x8c\x06corine\x94]\x94(K,K\xffe\x8c\x06natura\x94\x88\x8c\x0eship_threshold\x94M\x90\x01\x8c\x13excluder_resolution\x94K\xc8\x8c\tmin_depth\x94K<\x8c\tmax_depth\x94M\xe8\x03\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{\x8c\x0flandfall_length\x94K\nu\x8c\x05solar\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x02pv\x94\x8c\x05panel\x94\x8c\x03CSi\x94\x8c\x0borientation\x94}\x94(\x8c\x05slope\x94G@A\x80\x00\x00\x00\x00\x00\x8c\x07azimuth\x94G@f\x80\x00\x00\x00\x00\x00uu\x8c\x11capacity_per_sqkm\x94G@\x14ffffff\x8c\x06corine\x94]\x94(K\x01K\x02K\x03K\x04K\x05K\x06K\x07K\x08K\tK\nK\x0bK\x0cK\rK\x0eK\x0fK\x10K\x11K\x12K\x13K\x14K\x1aK\x1fK e\x8c\x05luisa\x94\x89\x8c\x06natura\x94\x88\x8c\x13excluder_resolution\x94Kd\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{u\x8c\nsolar-hsat\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08resource\x94}\x94(\x8c\x06method\x94\x8c\x02pv\x94\x8c\x05panel\x94\x8c\x03CSi\x94\x8c\x0borientation\x94}\x94(\x8c\x05slope\x94G@A\x80\x00\x00\x00\x00\x00\x8c\x07azimuth\x94G@f\x80\x00\x00\x00\x00\x00u\x8c\x08tracking\x94\x8c\nhorizontal\x94u\x8c\x11capacity_per_sqkm\x94G@\x11\xb8Q\xeb\x85\x1e\xb8\x8c\x06corine\x94]\x94(K\x01K\x02K\x03K\x04K\x05K\x06K\x07K\x08K\tK\nK\x0bK\x0cK\rK\x0eK\x0fK\x10K\x11K\x12K\x13K\x14K\x1aK\x1fK e\x8c\x05luisa\x94\x89\x8c\x06natura\x94\x88\x8c\x13excluder_resolution\x94Kd\x8c\rclip_p_max_pu\x94G?\x84z\xe1G\xae\x14{u\x8c\x05hydro\x94}\x94(\x8c\x06cutout\x94\x8c\x17europe-2013-sarah3-era5\x94\x8c\x08carriers\x94]\x94(\x8c\x03ror\x94\x8c\x03PHS\x94\x8c\x05hydro\x94e\x8c\rPHS_max_hours\x94K\x06\x8c\x0fhydro_max_hours\x94\x8c!energy_capacity_totals_by_country\x94\x8c\x10flatten_dispatch\x94\x89\x8c\x17flatten_dispatch_buffer\x94G?\xc9\x99\x99\x99\x99\x99\x9a\x8c\x0fclip_min_inflow\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\reia_norm_year\x94\x89\x8c\x17eia_correct_by_capacity\x94\x89\x8c\x17eia_approximate_missing\x94\x89uu\x8c\x0cconventional\x94}\x94(\x8c\x0funit_commitment\x94\x89\x8c\x12dynamic_fuel_price\x94\x89\x8c\x07nuclear\x94}\x94\x8c\x08p_max_pu\x94\x8c\x19data/nuclear_p_max_pu.csv\x94su\x8c\x0ctransformers\x94}\x94(j_\x02\x00\x00G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\x05s_nom\x94G@\x9f@\x00\x00\x00\x00\x00\x8c\x04type\x94h\x8cu\x8c\x04load\x94}\x94(\x8c\x11interpolate_limit\x94K\x03\x8c\x19time_shift_for_large_gaps\x94\x8c\x021w\x94\x8c\x12manual_adjustments\x94\x88\x8c\x0escaling_factor\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\nfixed_year\x94\x89\x8c\x14supplement_synthetic\x94\x88\x8c\x10distribution_key\x94}\x94(\x8c\x03gdp\x94G?\xe3333333\x8c\npopulation\x94G?\xd9\x99\x99\x99\x99\x99\x9auu\x8c\tpypsa_eur\x94}\x94(\x8c\x03Bus\x94]\x94\x8c\x02AC\x94a\x8c\x04Link\x94]\x94\x8c\x02DC\x94a\x8c\tGenerator\x94]\x94(\x8c\x06onwind\x94\x8c\noffwind-ac\x94\x8c\noffwind-dc\x94\x8c\roffwind-float\x94\x8c\nsolar-hsat\x94\x8c\x05solar\x94\x8c\x03ror\x94\x8c\x07nuclear\x94e\x8c\x0bStorageUnit\x94]\x94(\x8c\x03PHS\x94\x8c\x05hydro\x94e\x8c\x05Store\x94]\x94u\x8c\x06energy\x94}\x94(\x8c\x12energy_totals_year\x94M\xe3\x07\x8c\x13base_emissions_year\x94M\xc6\x07\x8c\temissions\x94\x8c\x03CO2\x94u\x8c\x07biomass\x94}\x94(\x8c\x04year\x94M\xee\x07\x8c\x08scenario\x94\x8c\x07ENS_Med\x94\x8c\x07classes\x94}\x94(\x8c\rsolid biomass\x94]\x94(\x8c\x12Agricultural waste\x94\x8c\x11Fuelwood residues\x94\x8c\'Secondary Forestry residues - woodchips\x94\x8c\x07Sawdust\x94\x8c\x1cResidues from landscape care\x94e\x8c\x0cnot included\x94]\x94(\x8c\x15Sugar from sugar beet\x94\x8c\tRape seed\x94\x8c\x15Sunflower, soya seed \x94\x8cBBioethanol barley, wheat, grain maize, oats, other cereals and rye\x94\x8c\x1cMiscanthus, switchgrass, RCG\x94\x8c\x06Willow\x94\x8c\x06Poplar\x94\x8c\nFuelwoodRW\x94\x8c\x06C&P_RW\x94e\x8c\x06biogas\x94]\x94(\x8c\x14Manure solid, liquid\x94\x8c\x06Sludge\x94e\x8c\x15municipal solid waste\x94]\x94\x8c\x0fMunicipal waste\x94au\x8c share_unsustainable_use_retained\x94}\x94(M\xe4\x07K\x01M\xe9\x07G?\xe5\x1e\xb8Q\xeb\x85\x1fM\xee\x07G?\xd5\x1e\xb8Q\xeb\x85\x1fM\xf3\x07K\x00M\xf8\x07K\x00M\xfd\x07K\x00M\x02\x08K\x00u\x8c%share_sustainable_potential_available\x94}\x94(M\xe4\x07K\x00M\xe9\x07G?\xd5\x1e\xb8Q\xeb\x85\x1fM\xee\x07G?\xe5\x1e\xb8Q\xeb\x85\x1fM\xf3\x07K\x01M\xf8\x07K\x01M\xfd\x07K\x01M\x02\x08K\x01uu\x8c\rsolar_thermal\x94}\x94(\x8c\x0eclearsky_model\x94\x8c\x06simple\x94\x8c\x0borientation\x94}\x94(\x8c\x05slope\x94G@F\x80\x00\x00\x00\x00\x00\x8c\x07azimuth\x94G@f\x80\x00\x00\x00\x00\x00u\x8c\x06cutout\x94\x8c\x07default\x94u\x8c\x13existing_capacities\x94}\x94(\x8c\x14grouping_years_power\x94]\x94(M\x80\x07M\x9e\x07M\xa3\x07M\xa8\x07M\xad\x07M\xb2\x07M\xb7\x07M\xbc\x07M\xc1\x07M\xc6\x07M\xcb\x07M\xd0\x07M\xd5\x07M\xda\x07M\xdf\x07M\xe4\x07M\xe9\x07e\x8c\x13grouping_years_heat\x94]\x94(M\xbc\x07M\xc1\x07M\xc6\x07M\xcb\x07M\xd0\x07M\xd5\x07M\xda\x07M\xdf\x07M\xe3\x07e\x8c\x12threshold_capacity\x94K\n\x8c\x18default_heating_lifetime\x94K\x14\x8c\x15conventional_carriers\x94]\x94(\x8c\x07lignite\x94\x8c\x04coal\x94\x8c\x03oil\x94\x8c\x07uranium\x94eu\x8c\x06sector\x94}\x94(\x8c\ttransport\x94\x88\x8c\x07heating\x94\x88\x8c\x07biomass\x94\x88\x8c\x08industry\x94\x88\x8c\x08shipping\x94\x88\x8c\x08aviation\x94\x88\x8c\x0bagriculture\x94\x88\x8c\x0cfossil_fuels\x94\x88\x8c\x10district_heating\x94}\x94(\x8c\tpotential\x94G?\xe3333333\x8c\x08progress\x94}\x94(M\xe4\x07G\x00\x00\x00\x00\x00\x00\x00\x00M\xe9\x07G?\xc3333333M\xee\x07G?\xd3333333M\xf3\x07G?\xdc\xcc\xcc\xcc\xcc\xcc\xcdM\xf8\x07G?\xe3333333M\xfd\x07G?\xe9\x99\x99\x99\x99\x99\x9aM\x02\x08G?\xf0\x00\x00\x00\x00\x00\x00u\x8c\x15district_heating_loss\x94G?\xc3333333\x8c supply_temperature_approximation\x94}\x94(\x8c max_forward_temperature_baseyear\x94}\x94(\x8c\x02FR\x94Kn\x8c\x02DK\x94KK\x8c\x02DE\x94Km\x8c\x02CZ\x94K\x82\x8c\x02FI\x94Ks\x8c\x02PL\x94K\x82\x8c\x02SE\x94Kf\x8c\x02IT\x94KZu\x8c min_forward_temperature_baseyear\x94}\x94\x8c\x02DE\x94KRs\x8c\x1breturn_temperature_baseyear\x94}\x94\x8c\x02DE\x94K:s\x8c#lower_threshold_ambient_temperature\x94K\x00\x8c#upper_threshold_ambient_temperature\x94K\n\x8c"rolling_window_ambient_temperature\x94KH\x8c%relative_annual_temperature_reduction\x94G?\x84z\xe1G\xae\x14{u\x8c\x04ptes\x94}\x94(\x8c\x10dynamic_capacity\x94\x88\x8c\x13max_top_temperature\x94KZ\x8c\x16min_bottom_temperature\x94K#u\x8c\x13heat_source_cooling\x94K\x06\x8c\x1bheat_pump_cop_approximation\x94}\x94(\x8c\x0brefrigerant\x94\x8c\x07ammonia\x94\x8c1heat_exchanger_pinch_point_temperature_difference\x94K\x05\x8c isentropic_compressor_efficiency\x94G?\xe9\x99\x99\x99\x99\x99\x9a\x8c\theat_loss\x94G\x00\x00\x00\x00\x00\x00\x00\x00u\x8c\x14limited_heat_sources\x94}\x94\x8c\ngeothermal\x94}\x94\x8c\x1cconstant_temperature_celsius\x94KAss\x8c\x1fdirect_utilisation_heat_sources\x94]\x94\x8c\ngeothermal\x94au\x8c\x11heat_pump_sources\x94}\x94(\x8c\rurban central\x94]\x94\x8c\x03air\x94a\x8c\x0furban decentral\x94]\x94\x8c\x03air\x94a\x8c\x05rural\x94]\x94(\x8c\x03air\x94\x8c\x06ground\x94eu\x8c\x12cluster_heat_buses\x94\x88\x8c\x12heat_demand_cutout\x94\x8c\x07default\x94\x8c\x19bev_dsm_restriction_value\x94G?\xe8\x00\x00\x00\x00\x00\x00\x8c\x18bev_dsm_restriction_time\x94K\x07\x8c transport_heating_deadband_upper\x94G@4\x00\x00\x00\x00\x00\x00\x8c transport_heating_deadband_lower\x94G@.\x00\x00\x00\x00\x00\x00\x8c\x17ICE_lower_degree_factor\x94G?\xd8\x00\x00\x00\x00\x00\x00\x8c\x17ICE_upper_degree_factor\x94G?\xf9\x99\x99\x99\x99\x99\x9a\x8c\x16EV_lower_degree_factor\x94G?\xef\\(\xf5\xc2\x8f\\\x8c\x16EV_upper_degree_factor\x94G?\xe4(\xf5\xc2\x8f\\)\x8c\x07bev_dsm\x94\x88\x8c\x14bev_dsm_availability\x94G?\xe0\x00\x00\x00\x00\x00\x00\x8c\nbev_energy\x94G?\xa9\x99\x99\x99\x99\x99\x9a\x8c\x15bev_charge_efficiency\x94G?\xec\xcc\xcc\xcc\xcc\xcc\xcd\x8c\x0fbev_charge_rate\x94G?\x86\x87+\x02\x0cI\xba\x8c\rbev_avail_max\x94G?\xeeffffff\x8c\x0ebev_avail_mean\x94G?\xe9\x99\x99\x99\x99\x99\x9a\x8c\x03v2g\x94\x88\x8c\x1eland_transport_fuel_cell_share\x94}\x94(M\xe4\x07K\x00M\xe9\x07K\x00M\xee\x07K\x00M\xf3\x07K\x00M\xf8\x07K\x00M\xfd\x07K\x00M\x02\x08K\x00u\x8c\x1dland_transport_electric_share\x94}\x94(M\xe4\x07K\x00M\xe9\x07G?\xc3333333M\xee\x07G?\xd3333333M\xf3\x07G?\xdc\xcc\xcc\xcc\xcc\xcc\xcdM\xf8\x07G?\xe6ffffffM\xfd\x07G?\xeb333333M\x02\x08K\x01u\x8c\x18land_transport_ice_share\x94}\x94(M\xe4\x07K\x01M\xe9\x07G?\xeb333333M\xee\x07G?\xe6ffffffM\xf3\x07G?\xe1\x99\x99\x99\x99\x99\x9aM\xf8\x07G?\xd3333333M\xfd\x07G?\xc3333333M\x02\x08K\x00u\x8c\x1dtransport_electric_efficiency\x94G@J\x98Q\xeb\x85\x1e\xb8\x8c\x1etransport_fuel_cell_efficiency\x94G@>\x00\xc4\x9b\xa5\xe3T\x8c\x18transport_ice_efficiency\x94G@0\x12:)\xc7y\xa7\x8c$agriculture_machinery_electric_share\x94K\x00\x8c\x1fagriculture_machinery_oil_share\x94K\x01\x8c%agriculture_machinery_fuel_efficiency\x94G?\xe6ffffff\x8c)agriculture_machinery_electric_efficiency\x94G?\xd3333333\x8c\x13MWh_MeOH_per_MWh_H2\x94G?\xec\x1eOv_\xd8\xae\x8c\x11MWh_MeOH_per_tCO2\x94G@\x10 \xde\xd2\x88\xcep\x8c\x12MWh_MeOH_per_MWh_e\x94G@\r\x86\x8d\xb8\xba\xc7\x11\x8c\x1eshipping_hydrogen_liquefaction\x94\x89\x8c\x17shipping_hydrogen_share\x94}\x94(M\xe4\x07K\x00M\xe9\x07K\x00M\xee\x07K\x00M\xf3\x07K\x00M\xf8\x07K\x00M\xfd\x07K\x00M\x02\x08K\x00u\x8c\x17shipping_methanol_share\x94}\x94(M\xe4\x07K\x00M\xe9\x07G?\xc3333333M\xee\x07G?\xd3333333M\xf3\x07G?\xe0\x00\x00\x00\x00\x00\x00M\xf8\x07G?\xe6ffffffM\xfd\x07G?\xeb333333M\x02\x08K\x01u\x8c\x12shipping_oil_share\x94}\x94(M\xe4\x07K\x01M\xe9\x07G?\xeb333333M\xee\x07G?\xe6ffffffM\xf3\x07G?\xe0\x00\x00\x00\x00\x00\x00M\xf8\x07G?\xd3333333M\xfd\x07G?\xc3333333M\x02\x08K\x00u\x8c\x1cshipping_methanol_efficiency\x94G?\xddp\xa3\xd7\n=q\x8c\x17shipping_oil_efficiency\x94G?\xd9\x99\x99\x99\x99\x99\x9a\x8c\x16aviation_demand_factor\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\x11HVC_demand_factor\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\x0ftime_dep_hp_cop\x94\x88\x8c#heat_pump_sink_T_individual_heating\x94G@K\x80\x00\x00\x00\x00\x00\x8c\x1dreduce_space_heat_exogenously\x94\x88\x8c$reduce_space_heat_exogenously_factor\x94}\x94(M\xe4\x07G?\xb9\x99\x99\x99\x99\x99\x9aM\xe9\x07G?\xb7\n=p\xa3\xd7\nM\xee\x07G?\xb7\n=p\xa3\xd7\nM\xf3\x07G?\xbc(\xf5\xc2\x8f\\)M\xf8\x07G?\xc4z\xe1G\xae\x14{M\xfd\x07G?\xca\xe1G\xae\x14z\xe1M\x02\x08G?\xd2\x8f\\(\xf5\xc2\x8fu\x8c\x0cretrofitting\x94}\x94(\x8c\rretro_endogen\x94\x89\x8c\x0bcost_factor\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rinterest_rate\x94G?\xa4z\xe1G\xae\x14{\x8c\x0eannualise_cost\x94\x88\x8c\rtax_weighting\x94\x89\x8c\x12construction_index\x94\x88u\x8c\x03tes\x94\x88\x8c\x07tes_tau\x94}\x94(\x8c\tdecentral\x94K\x03\x8c\x07central\x94K\xb4u\x8c\x07boilers\x94\x88\x8c\x11resistive_heaters\x94\x88\x8c\x0boil_boilers\x94\x89\x8c\x0ebiomass_boiler\x94\x88\x8c\x1doverdimension_heat_generators\x94}\x94(\x8c\tdecentral\x94G?\xf1\x99\x99\x99\x99\x99\x9a\x8c\x07central\x94G?\xf0\x00\x00\x00\x00\x00\x00u\x8c\x03chp\x94}\x94(\x8c\x06enable\x94\x88\x8c\x04fuel\x94]\x94(\x8c\rsolid biomass\x94\x8c\x03gas\x94e\x8c\tmicro_chp\x94\x89u\x8c\rsolar_thermal\x94\x88\x8c\x13solar_cf_correction\x94G?\xe9;\n,\xa9\xac6\x8c\x0bmethanation\x94\x88\x8c\x07coal_cc\x94\x89\x8c\x03dac\x94\x88\x8c\x08co2_vent\x94\x89\x8c\theat_vent\x94}\x94(\x8c\rurban central\x94\x88\x8c\x0furban decentral\x94\x88\x8c\x05rural\x94\x88u\x8c\x17marginal_cost_heat_vent\x94G?\x94z\xe1G\xae\x14{\x8c\x0fallam_cycle_gas\x94\x89\x8c\x12hydrogen_fuel_cell\x94\x88\x8c\x10hydrogen_turbine\x94\x89\x8c\x03SMR\x94\x88\x8c\x06SMR_cc\x94\x88\x8c\x13regional_oil_demand\x94\x89\x8c\x14regional_coal_demand\x94\x89\x8c$regional_co2_sequestration_potential\x94}\x94(\x8c\x06enable\x94\x89\x8c\tattribute\x94]\x94(\x8c\x18conservative estimate Mt\x94\x8c\x1cconservative estimate GAS Mt\x94\x8c\x1cconservative estimate OIL Mt\x94\x8c conservative estimate aquifer Mt\x94e\x8c\x0finclude_onshore\x94\x89\x8c\x08min_size\x94K\x03\x8c\x08max_size\x94K\x19\x8c\x10years_of_storage\x94K\x19u\x8c\x1bco2_sequestration_potential\x94}\x94(M\xe4\x07K\x00M\xe9\x07K\x00M\xee\x07K2M\xf3\x07KdM\xf8\x07K\xc8M\xfd\x07K\xc8M\x02\x08K\xc8u\x8c\x16co2_sequestration_cost\x94K\n\x8c\x1aco2_sequestration_lifetime\x94K2\x8c\x0bco2_spatial\x94\x89\x8c\x0bco2_network\x94\x89\x8c\x17co2_network_cost_factor\x94K\x01\x8c\x0bcc_fraction\x94G?\xec\xcc\xcc\xcc\xcc\xcc\xcd\x8c\x1chydrogen_underground_storage\x94\x88\x8c&hydrogen_underground_storage_locations\x94]\x94\x8c\tnearshore\x94a\x8c\x08methanol\x94}\x94(\x8c\x18regional_methanol_demand\x94\x89\x8c\x12methanol_reforming\x94\x89\x8c\x15methanol_reforming_cc\x94\x89\x8c\x14methanol_to_kerosene\x94\x89\x8c\x11methanol_to_power\x94}\x94(\x8c\x04ccgt\x94\x89\x8c\x07ccgt_cc\x94\x89\x8c\x04ocgt\x94\x89\x8c\x05allam\x94\x89u\x8c\x13biomass_to_methanol\x94\x89\x8c\x16biomass_to_methanol_cc\x94\x89u\x8c\x07ammonia\x94\x89\x8c\x1dmin_part_load_fischer_tropsch\x94G?\xe0\x00\x00\x00\x00\x00\x00\x8c\x1dmin_part_load_methanolisation\x94G?\xd3333333\x8c\x19min_part_load_methanation\x94G?\xd3333333\x8c\x1euse_fischer_tropsch_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x1ause_haber_bosch_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x1euse_methanolisation_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x1ause_methanation_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x18use_fuel_cell_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x1buse_electrolysis_waste_heat\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x1delectricity_transmission_grid\x94\x88\x8c\x1delectricity_distribution_grid\x94\x88\x8c\x1belectricity_grid_connection\x94\x88\x8c\x17transmission_efficiency\x94}\x94(\x8c\x02DC\x94}\x94(\x8c\x11efficiency_static\x94G?\xef\\(\xf5\xc2\x8f\\\x8c\x15efficiency_per_1000km\x94G?\xefC\x95\x81\x06$\xddu\x8c\x0bH2 pipeline\x94}\x94(\x8c\x15efficiency_per_1000km\x94K\x01\x8c\x16compression_per_1000km\x94G?\x92n\x97\x8dO\xdf;u\x8c\x0cgas pipeline\x94}\x94(\x8c\x15efficiency_per_1000km\x94K\x01\x8c\x16compression_per_1000km\x94G?\x84z\xe1G\xae\x14{u\x8c\x1delectricity distribution grid\x94}\x94\x8c\x11efficiency_static\x94G?\xef\n=p\xa3\xd7\nsu\x8c\nH2_network\x94\x88\x8c\x0bgas_network\x94\x89\x8c\x0bH2_retrofit\x94\x89\x8c\x1cH2_retrofit_capacity_per_CH4\x94G?\xe3333333\x8c gas_network_connectivity_upgrade\x94K\x01\x8c\x15gas_distribution_grid\x94\x88\x8c!gas_distribution_grid_cost_factor\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\x0fbiomass_spatial\x94\x89\x8c\x11biomass_transport\x94\x89\x8c\x13biogas_upgrading_cc\x94\x89\x8c\x17conventional_generation\x94}\x94\x8c\x04OCGT\x94\x8c\x03gas\x94s\x8c\x11biomass_to_liquid\x94\x89\x8c\x14biomass_to_liquid_cc\x94\x89\x8c\x0felectrobiofuels\x94\x89\x8c\x06biosng\x94\x89\x8c\tbiosng_cc\x94\x89\x8c\x05bioH2\x94\x89\x8c\x15municipal_solid_waste\x94\x89\x8c\x10limit_max_growth\x94}\x94(\x8c\x06enable\x94\x89\x8c\x06factor\x94G?\xf4\xcc\xcc\xcc\xcc\xcc\xcd\x8c\nmax_growth\x94}\x94(\x8c\x06onwind\x94K\x10\x8c\x05solar\x94K\x1c\x8c\noffwind-ac\x94K#\x8c\noffwind-dc\x94K#u\x8c\x13max_relative_growth\x94}\x94(\x8c\x06onwind\x94K\x03\x8c\x05solar\x94K\x03\x8c\noffwind-ac\x94K\x03\x8c\noffwind-dc\x94K\x03uu\x8c\x13enhanced_geothermal\x94}\x94(\x8c\x06enable\x94\x89\x8c\x08flexible\x94\x88\x8c\tmax_hours\x94K\xf0\x8c\tmax_boost\x94G?\xd0\x00\x00\x00\x00\x00\x00\x8c\x06var_cf\x94\x88\x8c\x15sustainability_factor\x94G?dz\xe1G\xae\x14{u\x8c\x14solid_biomass_import\x94}\x94(\x8c\x06enable\x94\x89\x8c\x05price\x94K6\x8c\nmax_amount\x94Mn\x05\x8c\x19upstream_emissions_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9au\x8c\x07imports\x94}\x94(\x8c\x06enable\x94\x89\x8c\x05limit\x94G\x7f\xf0\x00\x00\x00\x00\x00\x00\x8c\x0blimit_sense\x94\x8c\x02<=\x94\x8c\x05price\x94}\x94(\x8c\x02H2\x94KJ\x8c\x03NH3\x94Ka\x8c\x08methanol\x94Ky\x8c\x03gas\x94Kz\x8c\x03oil\x94K}uuu\x8c\x08industry\x94}\x94(\x8c\x13St_primary_fraction\x94}\x94(M\xe4\x07G?\xe3333333M\xe9\x07G?\xe1\x99\x99\x99\x99\x99\x9aM\xee\x07G?\xe0\x00\x00\x00\x00\x00\x00M\xf3\x07G?\xdc\xcc\xcc\xcc\xcc\xcc\xcdM\xf8\x07G?\xd9\x99\x99\x99\x99\x99\x9aM\xfd\x07G?\xd6ffffffM\x02\x08G?\xd3333333u\x8c\x0cDRI_fraction\x94}\x94(M\xe4\x07K\x00M\xe9\x07K\x00M\xee\x07G?\xa9\x99\x99\x99\x99\x99\x9aM\xf3\x07G?\xc9\x99\x99\x99\x99\x99\x9aM\xf8\x07G?\xd9\x99\x99\x99\x99\x99\x9aM\xfd\x07G?\xe6ffffffM\x02\x08K\x01u\x8c\x06H2_DRI\x94G?\xfb333333\x8c\x08elec_DRI\x94G?\xd4\x9b\xa5\xe3S\xf7\xcf\x8c\x13Al_primary_fraction\x94}\x94(M\xe4\x07G?\xd9\x99\x99\x99\x99\x99\x9aM\xe9\x07G?\xd8\x00\x00\x00\x00\x00\x00M\xee\x07G?\xd6ffffffM\xf3\x07G?\xd4\xcc\xcc\xcc\xcc\xcc\xcdM\xf8\x07G?\xd3333333M\xfd\x07G?\xd0\x00\x00\x00\x00\x00\x00M\x02\x08G?\xc9\x99\x99\x99\x99\x99\x9au\x8c\x10MWh_NH3_per_tNH3\x94G@\x14\xa9\xfb\xe7l\x8bD\x8c\x14MWh_CH4_per_tNH3_SMR\x94G@%\x99\x99\x99\x99\x99\x9a\x8c\x15MWh_elec_per_tNH3_SMR\x94G?\xe6ffffff\x8c\x1cMWh_H2_per_tNH3_electrolysis\x94G@\x17\xb8Q\xeb\x85\x1e\xb8\x8c\x1eMWh_elec_per_tNH3_electrolysis\x94G?\xcf\xa7\x86\xc2&\x80\x9d\x8c\x1aMWh_NH3_per_MWh_H2_cracker\x94G?\xf7\\(\xf5\xc2\x8f\\\x8c\x15NH3_process_emissions\x94G@8\x80\x00\x00\x00\x00\x00\x8c\x1fpetrochemical_process_emissions\x94G@9\x80\x00\x00\x00\x00\x00\x8c\x14HVC_primary_fraction\x94}\x94(M\xe4\x07G?\xf0\x00\x00\x00\x00\x00\x00M\xe9\x07G?\xec\xcc\xcc\xcc\xcc\xcc\xcdM\xee\x07G?\xe9\x99\x99\x99\x99\x99\x9aM\xf3\x07G?\xe6ffffffM\xf8\x07G?\xe3333333M\xfd\x07G?\xe0\x00\x00\x00\x00\x00\x00M\x02\x08G?\xd9\x99\x99\x99\x99\x99\x9au\x8c!HVC_mechanical_recycling_fraction\x94}\x94(M\xe4\x07G?\xbe\xb8Q\xeb\x85\x1e\xb8M\xe9\x07G?\xc3333333M\xee\x07G?\xc7\n=p\xa3\xd7\nM\xf3\x07G?\xca\xe1G\xae\x14z\xe1M\xf8\x07G?\xce\xb8Q\xeb\x85\x1e\xb8M\xfd\x07G?\xd1G\xae\x14z\xe1HM\x02\x08G?\xd3333333u\x8c\x1fHVC_chemical_recycling_fraction\x94}\x94(M\xe4\x07G\x00\x00\x00\x00\x00\x00\x00\x00M\xe9\x07G\x00\x00\x00\x00\x00\x00\x00\x00M\xee\x07G?\xa4z\xe1G\xae\x14{M\xf3\x07G?\xb4z\xe1G\xae\x14{M\xf8\x07G?\xbe\xb8Q\xeb\x85\x1e\xb8M\xfd\x07G?\xc4z\xe1G\xae\x14{M\x02\x08G?\xc9\x99\x99\x99\x99\x99\x9au\x8c&HVC_environment_sequestration_fraction\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0fwaste_to_energy\x94\x89\x8c\x12waste_to_energy_cc\x94\x89\x8c\x1dsector_ratios_fraction_future\x94}\x94(M\xe4\x07G\x00\x00\x00\x00\x00\x00\x00\x00M\xe9\x07G?\xb9\x99\x99\x99\x99\x99\x9aM\xee\x07G?\xd3333333M\xf3\x07G?\xe0\x00\x00\x00\x00\x00\x00M\xf8\x07G?\xe6ffffffM\xfd\x07G?\xec\xcc\xcc\xcc\xcc\xcc\xcdM\x02\x08G?\xf0\x00\x00\x00\x00\x00\x00u\x8c,basic_chemicals_without_NH3_production_today\x94G@Q@\x00\x00\x00\x00\x00\x8c\x14HVC_production_today\x94G@J\x00\x00\x00\x00\x00\x00\x8c&MWh_elec_per_tHVC_mechanical_recycling\x94G?\xe1\x81\x06$\xdd/\x1b\x8c$MWh_elec_per_tHVC_chemical_recycling\x94G@\x1b\x99\x99\x99\x99\x99\x9a\x8c\x19chlorine_production_today\x94G@#(\xf5\xc2\x8f\\)\x8c\x10MWh_elec_per_tCl\x94G@\x0c\xcc\xcc\xcc\xcc\xcc\xcd\x8c\x0eMWh_H2_per_tCl\x94G\xbf\xed\xfd\x8a\xda\xb9\xf5Z\x8c\x19methanol_production_today\x94G?\xf8\x00\x00\x00\x00\x00\x00\x8c\x12MWh_elec_per_tMeOH\x94G?\xc5`A\x897K\xc7\x8c\x11MWh_CH4_per_tMeOH\x94G@$\x80\x00\x00\x00\x00\x00\x8c\x12MWh_MeOH_per_tMeOH\x94G@\x16\x1c\xac\x081&\xe9\x8c\x16hotmaps_locate_missing\x94\x89\x8c\x0ereference_year\x94M\xe3\x07\x8c\x16oil_refining_emissions\x94G?\x8a\x9f\xbev\xc8\xb49u\x8c\x05costs\x94}\x94(\x8c\x04year\x94M\xee\x07\x8c\x07version\x94\x8c\x07v0.10.1\x94\x8c\x13social_discountrate\x94G?\x94z\xe1G\xae\x14{\x8c\x0bfill_values\x94}\x94(\x8c\x03FOM\x94K\x00\x8c\x03VOM\x94K\x00\x8c\nefficiency\x94K\x01\x8c\x04fuel\x94K\x00\x8c\ninvestment\x94K\x00\x8c\x08lifetime\x94K\x19\x8c\rCO2 intensity\x94K\x00\x8c\rdiscount rate\x94G?\xb1\xeb\x85\x1e\xb8Q\xecu\x8c\noverwrites\x94}\x94\x8c\rmarginal_cost\x94}\x94(\x8c\x05solar\x94G?\x84z\xe1G\xae\x14{\x8c\x06onwind\x94G?\x8e\xb8Q\xeb\x85\x1e\xb8\x8c\x07offwind\x94G?\x8e\xb8Q\xeb\x85\x1e\xb8\x8c\x05hydro\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x02H2\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0celectrolysis\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\tfuel cell\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x07battery\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x10battery inverter\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x14home battery storage\x94K\x00\x8c\x12water tank charger\x94G?\x9e\xb8Q\xeb\x85\x1e\xb8\x8c\x19central water pit charger\x94G?\x99\x99\x99\x99\x99\x99\x9au\x8c\x0femission_prices\x94}\x94(\x8c\x06enable\x94\x89\x8c\x03co2\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x12co2_monthly_prices\x94\x89uu\x8c\x0badjustments\x94}\x94(\x8c\x0belectricity\x94\x89\x8c\x06sector\x94}\x94(\x8c\x06factor\x94}\x94\x8c\x04Link\x94}\x94\x8c\x1delectricity distribution grid\x94}\x94\x8c\x0ccapital_cost\x94G?\xf0\x00\x00\x00\x00\x00\x00sss\x8c\x08absolute\x94\x89uu\x8c\x08plotting\x94}\x94(\x8c\x03map\x94}\x94(\x8c\nboundaries\x94]\x94(J\xf5\xff\xff\xffK\x1eK"KGe\x8c\x0ccolor_geomap\x94}\x94(\x8c\x05ocean\x94\x8c\x05white\x94\x8c\x04land\x94\x8c\x05white\x94uu\x8c\nprojection\x94}\x94\x8c\x04name\x94\x8c\nEqualEarth\x94s\x8c\x10eu_node_location\x94}\x94(j_\x02\x00\x00G\xc0\x16\x00\x00\x00\x00\x00\x00ja\x02\x00\x00G@G\x00\x00\x00\x00\x00\x00u\x8c\tcosts_max\x94M\xe8\x03\x8c\x0fcosts_threshold\x94K\x01\x8c\nenergy_max\x94M N\x8c\nenergy_min\x94J\xe0\xb1\xff\xff\x8c\x10energy_threshold\x94G@I\x00\x00\x00\x00\x00\x00\x8c\x12balance_timeseries\x94}\x94(\x8c\rmax_threshold\x94K\x05\x8c\x0emean_threshold\x94K\x01\x8c\x07monthly\x94\x88\x8c\x12monthly_resolution\x94N\x8c\x06annual\x94\x88\x8c\x11annual_resolution\x94\x8c\x01D\x94\x8c\x08carriers\x94]\x94(\x8c\x02H2\x94\x8c\x03NH3\x94\x8c\x03gas\x94\x8c\x08methanol\x94\x8c\x03oil\x94\x8c\rsolid biomass\x94\x8c\x06biogas\x94\x8c\nco2 stored\x94\x8c\x03co2\x94e\x8c\x0ecarrier_groups\x94}\x94(\x8c\x0belectricity\x94]\x94(\x8c\x02AC\x94\x8c\x0blow voltage\x94e\x8c\x04heat\x94]\x94(\x8c\x12urban central heat\x94\x8c\x14urban decentral heat\x94\x8c\nrural heat\x94\x8c residential urban decentral heat\x94\x8c\x16residential rural heat\x94\x8c\x1dservices urban decentral heat\x94\x8c\x13services rural heat\x94euu\x8c\x12heatmap_timeseries\x94}\x94(\x8c\x0emarginal_price\x94]\x94(\x8c\x02AC\x94\x8c\x02H2\x94\x8c\x03NH3\x94\x8c\x03gas\x94\x8c\x08methanol\x94\x8c\x03oil\x94\x8c\nco2 stored\x94\x8c\x12urban central heat\x94e\x8c\x10utilisation_rate\x94]\x94(\x8c\x05solar\x94\x8c\rsolar rooftop\x94\x8c\nsolar-hsat\x94\x8c\x06onwind\x94\x8c\noffwind-dc\x94\x8c\noffwind-ac\x94\x8c\roffwind-float\x94\x8c\x03ror\x94\x8c\x05hydro\x94\x8c\x03PHS\x94\x8c\x0fbattery charger\x94\x8c\x12battery discharger\x94\x8c\x0fH2 Electrolysis\x94\x8c\x0fFischer-Tropsch\x94\x8c\x0fmethanolisation\x94\x8c\x08Sabatier\x94\x8c\x04OCGT\x94\x8c\x0cH2 Fuel Cell\x94\x8c\x11urban central CHP\x94\x8c\x14urban central CHP CC\x94\x8c\x1furban central solid biomass CHP\x94\x8c"urban central solid biomass CHP CC\x94\x8c\x10rural gas boiler\x94\x8c\x1burban central air heat pump\x94\x8c\x03DAC\x94e\x8c\x03soc\x94]\x94(\x8c\x07battery\x94\x8c\x08H2 Store\x94\x8c\nco2 stored\x94\x8c\x03gas\x94\x8c\x08methanol\x94\x8c\x03oil\x94\x8c\x19urban central water tanks\x94eu\x8c\x0bbalance_map\x94}\x94(\x8c\x0cbus_carriers\x94]\x94(\x8c\x02AC\x94\x8c\x02H2\x94\x8c\x03gas\x94\x8c\x03oil\x94\x8c\x08methanol\x94\x8c\nco2 stored\x94\x8c\x12urban central heat\x94e\x8c\x02AC\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x06Greens\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?`bM\xd2\xf1\xa9\xfc\x8c\rbranch_factor\x94G?\x84z\xe1G\xae\x14{\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(K\xc8Kde\x8c\x0cbranch_sizes\x94]\x94(KdK\x14eu\x8c\x03gas\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x07Purples\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?`bM\xd2\xf1\xa9\xfc\x8c\rbranch_factor\x94G?\xa9\x99\x99\x99\x99\x99\x9a\x8c\x0bflow_factor\x94K<\x8c\tbus_sizes\x94]\x94(K\xc8Kde\x8c\x0cbranch_sizes\x94]\x94(KdK2eu\x8c\x02H2\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x05Blues\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?`bM\xd2\xf1\xa9\xfc\x8c\rbranch_factor\x94G?\xb1\xeb\x85\x1e\xb8Q\xec\x8c\x0bflow_factor\x94K2\x8c\tbus_sizes\x94]\x94(K2K\x19e\x8c\x0cbranch_sizes\x94]\x94(K(K\x14eu\x8c\nco2 stored\x94}\x94(\x8c\x04unit\x94\x8c\x02Mt\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x07Purples\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x0e\xe2\x82\xac/t_${CO_2}$\x94\x8c\nbus_factor\x94G?\x9e\xb8Q\xeb\x85\x1e\xb8\x8c\rbranch_factor\x94K\x01\x8c\x0bflow_factor\x94M\xd0\x07\x8c\tbus_sizes\x94]\x94(K2K\ne\x8c\x0cbranch_sizes\x94]\x94(K\x05K\x02eu\x8c\x12urban central heat\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x07Oranges\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?tz\xe1G\xae\x14{\x8c\rbranch_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(M,\x01Kde\x8c\x0cbranch_sizes\x94Nu\x8c\x08methanol\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x06Greens\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?tz\xe1G\xae\x14{\x8c\rbranch_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(K\x14K\ne\x8c\x0cbranch_sizes\x94Nu\x8c\x06biogas\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x06Greens\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\rbranch_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(KdK2e\x8c\x0cbranch_sizes\x94Nu\x8c\rsolid biomass\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x06Greens\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?\x84z\xe1G\xae\x14{\x8c\rbranch_factor\x94G?\xb9\x99\x99\x99\x99\x99\x9a\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(KdK2e\x8c\x0cbranch_sizes\x94Nu\x8c\x03oil\x94}\x94(\x8c\x04unit\x94\x8c\x03TWh\x94\x8c\x0funit_conversion\x94J@B\x0f\x00\x8c\x04cmap\x94\x8c\x05Greys\x94\x8c\x04vmin\x94N\x8c\x04vmax\x94N\x8c\x0bregion_unit\x94\x8c\x07\xe2\x82\xac/MWh\x94\x8c\nbus_factor\x94G?`bM\xd2\xf1\xa9\xfc\x8c\rbranch_factor\x94G?\x84z\xe1G\xae\x14{\x8c\x0bflow_factor\x94Kd\x8c\tbus_sizes\x94]\x94(K\xc8Kde\x8c\x0cbranch_sizes\x94Nuu\x8c\nnice_names\x94}\x94(\x8c\x04OCGT\x94\x8c\x0eOpen-Cycle Gas\x94\x8c\x04CCGT\x94\x8c\x12Combined-Cycle Gas\x94\x8c\noffwind-ac\x94\x8c\x12Offshore Wind (AC)\x94\x8c\noffwind-dc\x94\x8c\x12Offshore Wind (DC)\x94\x8c\roffwind-float\x94\x8c\x18Offshore Wind (Floating)\x94\x8c\x06onwind\x94\x8c\x0cOnshore Wind\x94\x8c\x05solar\x94\x8c\x05Solar\x94\x8c\x03PHS\x94\x8c\x14Pumped Hydro Storage\x94\x8c\x05hydro\x94\x8c\x0fReservoir & Dam\x94\x8c\x07battery\x94\x8c\x0fBattery Storage\x94\x8c\x02H2\x94\x8c\x10Hydrogen Storage\x94\x8c\x05lines\x94\x8c\x12Transmission Lines\x94\x8c\x03ror\x94\x8c\x0cRun of River\x94\x8c\x04load\x94\x8c\rLoad Shedding\x94\x8c\x02ac\x94\x8c\x02AC\x94\x8c\x02dc\x94\x8c\x02DC\x94u\x8c\x0btech_colors\x94}\x94(\x8c\x06onwind\x94\x8c\x07#235ebc\x94\x8c\x0conshore wind\x94\x8c\x07#235ebc\x94\x8c\x07offwind\x94\x8c\x07#6895dd\x94\x8c\roffshore wind\x94\x8c\x07#6895dd\x94\x8c\noffwind-ac\x94\x8c\x07#6895dd\x94\x8c\x12offshore wind (AC)\x94\x8c\x07#6895dd\x94\x8c\x10offshore wind ac\x94\x8c\x07#6895dd\x94\x8c\noffwind-dc\x94\x8c\x07#74c6f2\x94\x8c\x12offshore wind (DC)\x94\x8c\x07#74c6f2\x94\x8c\x10offshore wind dc\x94\x8c\x07#74c6f2\x94\x8c\roffwind-float\x94\x8c\x07#b5e2fa\x94\x8c\x15offshore wind (Float)\x94\x8c\x07#b5e2fa\x94\x8c\x13offshore wind float\x94\x8c\x07#b5e2fa\x94\x8c\x05hydro\x94\x8c\x07#298c81\x94\x8c\x0fhydro reservoir\x94\x8c\x07#298c81\x94\x8c\x03ror\x94\x8c\x07#3dbfb0\x94\x8c\x0crun of river\x94\x8c\x07#3dbfb0\x94\x8c\x10hydroelectricity\x94\x8c\x07#298c81\x94\x8c\x03PHS\x94\x8c\x07#51dbcc\x94\x8c\thydro+PHS\x94\x8c\x07#08ad97\x94\x8c\x05solar\x94\x8c\x07#f9d002\x94\x8c\x08solar PV\x94\x8c\x07#f9d002\x94\x8c\nsolar-hsat\x94\x8c\x07#fdb915\x94\x8c\rsolar thermal\x94\x8c\x07#ffbf2b\x94\x8c\x1fresidential rural solar thermal\x94\x8c\x07#f1c069\x94\x8c\x1cservices rural solar thermal\x94\x8c\x07#eabf61\x94\x8c)residential urban decentral solar thermal\x94\x8c\x07#e5bc5a\x94\x8c&services urban decentral solar thermal\x94\x8c\x07#dfb953\x94\x8c\x1burban central solar thermal\x94\x8c\x07#d7b24c\x94\x8c\rsolar rooftop\x94\x8c\x07#ffea80\x94\x8c\x04OCGT\x94\x8c\x07#e0986c\x94\x8c\rOCGT marginal\x94\x8c\x07#e0986c\x94\x8c\tOCGT-heat\x94\x8c\x07#e0986c\x94\x8c\ngas boiler\x94\x8c\x07#db6a25\x94\x8c\x0bgas boilers\x94\x8c\x07#db6a25\x94\x8c\x13gas boiler marginal\x94\x8c\x07#db6a25\x94\x8c\x1cresidential rural gas boiler\x94\x8c\x07#d4722e\x94\x8c&residential urban decentral gas boiler\x94\x8c\x07#cb7a36\x94\x8c\x19services rural gas boiler\x94\x8c\x07#c4813f\x94\x8c#services urban decentral gas boiler\x94\x8c\x07#ba8947\x94\x8c\x18urban central gas boiler\x94\x8c\x07#b0904f\x94\x8c\x03gas\x94\x8c\x07#e05b09\x94\x8c\nfossil gas\x94\x8c\x07#e05b09\x94\x8c\x0bnatural gas\x94\x8c\x07#e05b09\x94\x8c\rbiogas to gas\x94\x8c\x07#e36311\x94\x8c\x10biogas to gas CC\x94\x8c\x07#e51245\x94\x8c\x04CCGT\x94\x8c\x07#a85522\x94\x8c\rCCGT marginal\x94\x8c\x07#a85522\x94\x8c\x05allam\x94\x8c\x07#B98F76\x94\x8c"gas for industry co2 to atmosphere\x94\x8c\x07#692e0a\x94\x8c\x1egas for industry co2 to stored\x94\x8c\x07#8a3400\x94\x8c\x10gas for industry\x94\x8c\x07#853403\x94\x8c\x13gas for industry CC\x94\x8c\x07#692e0a\x94\x8c\x0cgas pipeline\x94\x8c\x07#ebbca0\x94\x8c\x10gas pipeline new\x94\x8c\x07#a87c62\x94\x8c\x03oil\x94\x8c\x07#c9c9c9\x94\x8c\x0boil primary\x94\x8c\x07#d2d2d2\x94\x8c\x0coil refining\x94\x8c\x07#e6e6e6\x94\x8c\x0cimported oil\x94\x8c\x07#a3a3a3\x94\x8c\noil boiler\x94\x8c\x07#adadad\x94\x8c\x1cresidential rural oil boiler\x94\x8c\x07#a9a9a9\x94\x8c\x19services rural oil boiler\x94\x8c\x07#a5a5a5\x94\x8c&residential urban decentral oil boiler\x94\x8c\x07#a1a1a1\x94\x8c\x18urban central oil boiler\x94\x8c\x07#9d9d9d\x94\x8c#services urban decentral oil boiler\x94\x8c\x07#999999\x94\x8c\x19agriculture machinery oil\x94\x8c\x07#949494\x94\x8c\x0cshipping oil\x94\x8c\x07#808080\x94\x8c\x12land transport oil\x94\x8c\x07#afafaf\x94\x8c\x07Nuclear\x94\x8c\x07#ff8c00\x94\x8c\x10Nuclear marginal\x94\x8c\x07#ff8c00\x94\x8c\x07nuclear\x94\x8c\x07#ff8c00\x94\x8c\x07uranium\x94\x8c\x07#ff8c00\x94\x8c\x04Coal\x94\x8c\x07#545454\x94\x8c\x04coal\x94\x8c\x07#545454\x94\x8c\rCoal marginal\x94\x8c\x07#545454\x94\x8c\x11coal for industry\x94\x8c\x07#343434\x94\x8c\x05solid\x94\x8c\x07#545454\x94\x8c\x07Lignite\x94\x8c\x07#826837\x94\x8c\x07lignite\x94\x8c\x07#826837\x94\x8c\x10Lignite marginal\x94\x8c\x07#826837\x94\x8c\x06biogas\x94\x8c\x07#e3d37d\x94\x8c\x07biomass\x94\x8c\x07#baa741\x94\x8c\rsolid biomass\x94\x8c\x07#baa741\x94\x8c\x15municipal solid waste\x94\x8c\x07#91ba41\x94\x8c\x14solid biomass import\x94\x8c\x07#d5ca8d\x94\x8c\x17solid biomass transport\x94\x8c\x07#baa741\x94\x8c\x1asolid biomass for industry\x94\x8c\x07#7a6d26\x94\x8c\x1dsolid biomass for industry CC\x94\x8c\x07#47411c\x94\x8c.solid biomass for industry co2 from atmosphere\x94\x8c\x07#736412\x94\x8c(solid biomass for industry co2 to stored\x94\x8c\x07#47411c\x94\x8c\x1furban central solid biomass CHP\x94\x8c\x07#9d9042\x94\x8c"urban central solid biomass CHP CC\x94\x8c\x07#6c5d28\x94\x8c\x0ebiomass boiler\x94\x8c\x07#8A9A5B\x94\x8c residential rural biomass boiler\x94\x8c\x07#a1a066\x94\x8c*residential urban decentral biomass boiler\x94\x8c\x07#b0b87b\x94\x8c\x1dservices rural biomass boiler\x94\x8c\x07#c6cf98\x94\x8c\'services urban decentral biomass boiler\x94\x8c\x07#dde5b5\x94\x8c\x11biomass to liquid\x94\x8c\x07#32CD32\x94\x8c\x1bunsustainable solid biomass\x94\x8c\x07#998622\x94\x8c\x18unsustainable bioliquids\x94\x8c\x07#32CD32\x94\x8c\x0felectrobiofuels\x94\x8c\x03red\x94\x8c\x06BioSNG\x94\x8c\x07#123456\x94\x8c\x19solid biomass to hydrogen\x94\x8c\x07#654321\x94\x8c\x05lines\x94\x8c\x07#6c9459\x94\x8c\x12transmission lines\x94\x8c\x07#6c9459\x94\x8c\x1delectricity distribution grid\x94\x8c\x07#97ad8c\x94\x8c\x0blow voltage\x94\x8c\x07#97ad8c\x94\x8c\rElectric load\x94\x8c\x07#110d63\x94\x8c\x0felectric demand\x94\x8c\x07#110d63\x94\x8c\x0belectricity\x94\x8c\x07#110d63\x94\x8c\x14industry electricity\x94\x8c\x07#2d2a66\x94\x8c\x18industry new electricity\x94\x8c\x07#2d2a66\x94\x8c\x17agriculture electricity\x94\x8c\x07#494778\x94\x8c\x07battery\x94\x8c\x07#ace37f\x94\x8c\x0fbattery storage\x94\x8c\x07#ace37f\x94\x8c\x0fbattery charger\x94\x8c\x07#88a75b\x94\x8c\x12battery discharger\x94\x8c\x07#5d4e29\x94\x8c\x0chome battery\x94\x8c\x07#80c944\x94\x8c\x14home battery storage\x94\x8c\x07#80c944\x94\x8c\x14home battery charger\x94\x8c\x07#5e8032\x94\x8c\x17home battery discharger\x94\x8c\x07#3c5221\x94\x8c\x0bBEV charger\x94\x8c\x07#baf238\x94\x8c\x03V2G\x94\x8c\x07#e5ffa8\x94\x8c\x11land transport EV\x94\x8c\x07#baf238\x94\x8c\x15land transport demand\x94\x8c\x07#38baf2\x94\x8c\nEV battery\x94\x8c\x07#baf238\x94\x8c\x0bwater tanks\x94\x8c\x07#e69487\x94\x8c\x1dresidential rural water tanks\x94\x8c\x07#f7b7a3\x94\x8c\x1aservices rural water tanks\x94\x8c\x07#f3afa3\x94\x8c\'residential urban decentral water tanks\x94\x8c\x07#f2b2a3\x94\x8c$services urban decentral water tanks\x94\x8c\x07#f1b4a4\x94\x8c\x19urban central water tanks\x94\x8c\x07#e9977d\x94\x8c\x11hot water storage\x94\x8c\x07#e69487\x94\x8c\x12hot water charging\x94\x8c\x07#e8998b\x94\x8c!urban central water tanks charger\x94\x8c\x07#b57a67\x94\x8c%residential rural water tanks charger\x94\x8c\x07#b4887c\x94\x8c/residential urban decentral water tanks charger\x94\x8c\x07#b39995\x94\x8c"services rural water tanks charger\x94\x8c\x07#b3abb0\x94\x8c,services urban decentral water tanks charger\x94\x8c\x07#b3becc\x94\x8c\x15hot water discharging\x94\x8c\x07#e99c8e\x94\x8c$urban central water tanks discharger\x94\x8c\x07#b9816e\x94\x8c(residential rural water tanks discharger\x94\x8c\x07#ba9685\x94\x8c2residential urban decentral water tanks discharger\x94\x8c\x07#baac9e\x94\x8c%services rural water tanks discharger\x94\x8c\x07#bbc2b8\x94\x8c/services urban decentral water tanks discharger\x94\x8c\x07#bdd8d3\x94\x8c\nwater pits\x94\x8c\x07#cc826a\x94\x8c\x12water pits charger\x94\x8c\x07#b36a5e\x94\x8c\x15water pits discharger\x94\x8c\x07#b37468\x94\x8c\x18urban central water pits\x94\x8c\x07#d96f4c\x94\x8c urban central water pits charger\x94\x8c\x07#a85d47\x94\x8c#urban central water pits discharger\x94\x8c\x07#b36452\x94\x8c\tHeat load\x94\x8c\x07#cc1f1f\x94\x8c\x04heat\x94\x8c\x07#cc1f1f\x94\x8c\theat vent\x94\x8c\x07#aa3344\x94\x8c\x0bheat demand\x94\x8c\x07#cc1f1f\x94\x8c\nrural heat\x94\x8c\x07#ff5c5c\x94\x8c\x16residential rural heat\x94\x8c\x07#ff7c7c\x94\x8c\x13services rural heat\x94\x8c\x07#ff9c9c\x94\x8c\x0ccentral heat\x94\x8c\x07#cc1f1f\x94\x8c\x12urban central heat\x94\x8c\x07#d15959\x94\x8c\x17urban central heat vent\x94\x8c\x07#a74747\x94\x8c\x0edecentral heat\x94\x8c\x07#750606\x94\x8c residential urban decentral heat\x94\x8c\x07#a33c3c\x94\x8c\x1dservices urban decentral heat\x94\x8c\x07#cc1f1f\x94\x8c!low-temperature heat for industry\x94\x8c\x07#8f2727\x94\x8c\x0cprocess heat\x94\x8c\x07#ff0000\x94\x8c\x10agriculture heat\x94\x8c\x07#d9a5a5\x94\x8c\nheat pumps\x94\x8c\x07#2fb537\x94\x8c\theat pump\x94\x8c\x07#2fb537\x94\x8c\rair heat pump\x94\x8c\x07#36eb41\x94\x8c)residential urban decentral air heat pump\x94\x8c\x07#48f74f\x94\x8c&services urban decentral air heat pump\x94\x8c\x07#5af95d\x94\x8c\x1cservices rural air heat pump\x94\x8c\x07#5af95d\x94\x8c\x1burban central air heat pump\x94\x8c\x07#6cfb6b\x94\x8c"urban central geothermal heat pump\x94\x8c\x07#4f2144\x94\x8c\x14geothermal heat pump\x94\x8c\x07#4f2144\x94\x8c"geothermal heat direct utilisation\x94\x8c\x07#ba91b1\x94\x8c\x10ground heat pump\x94\x8c\x07#2fb537\x94\x8c"residential rural ground heat pump\x94\x8c\x07#4f2144\x94\x8c\x1fresidential rural air heat pump\x94\x8c\x07#48f74f\x94\x8c\x1fservices rural ground heat pump\x94\x8c\x07#5af95d\x94\x8c\x07Ambient\x94\x8c\x07#98eb9d\x94\x8c\x03CHP\x94\x8c\x07#8a5751\x94\x8c\x15urban central gas CHP\x94\x8c\x07#8d5e56\x94\x8c\x06CHP CC\x94\x8c\x07#634643\x94\x8c\x18urban central gas CHP CC\x94\x8c\x07#6e4e4c\x94\x8c\x08CHP heat\x94\x8c\x07#8a5751\x94\x8c\x0cCHP electric\x94\x8c\x07#8a5751\x94\x8c\x10district heating\x94\x8c\x07#e8beac\x94\x8c\x10resistive heater\x94\x8c\x07#d8f9b8\x94\x8c"residential rural resistive heater\x94\x8c\x07#bef5b5\x94\x8c,residential urban decentral resistive heater\x94\x8c\x07#b2f1a9\x94\x8c\x1fservices rural resistive heater\x94\x8c\x07#a5ed9d\x94\x8c)services urban decentral resistive heater\x94\x8c\x07#98e991\x94\x8c\x1eurban central resistive heater\x94\x8c\x07#8cdf85\x94\x8c\x0cretrofitting\x94\x8c\x07#8487e8\x94\x8c\x15building retrofitting\x94\x8c\x07#8487e8\x94\x8c\x0fH2 for industry\x94\x8c\x07#f073da\x94\x8c\x0fH2 for shipping\x94\x8c\x07#ebaee0\x94\x8c\x02H2\x94\x8c\x07#bf13a0\x94\x8c\x08hydrogen\x94\x8c\x07#bf13a0\x94\x8c\x15retrofitted H2 boiler\x94\x8c\x07#e5a0d9\x94\x8c\x03SMR\x94\x8c\x07#870c71\x94\x8c\x06SMR CC\x94\x8c\x07#4f1745\x94\x8c\x0fH2 liquefaction\x94\x8c\x07#d647bd\x94\x8c\x10hydrogen storage\x94\x8c\x07#bf13a0\x94\x8c\x08H2 Store\x94\x8c\x07#bf13a0\x94\x8c\nH2 storage\x94\x8c\x07#bf13a0\x94\x8c\x18land transport fuel cell\x94\x8c\x07#6b3161\x94\x8c\x0bH2 pipeline\x94\x8c\x07#f081dc\x94\x8c\x17H2 pipeline retrofitted\x94\x8c\x07#ba99b5\x94\x8c\x0cH2 Fuel Cell\x94\x8c\x07#c251ae\x94\x8c\x0cH2 fuel cell\x94\x8c\x07#c251ae\x94\x8c\nH2 turbine\x94\x8c\x07#991f83\x94\x8c\x0fH2 Electrolysis\x94\x8c\x07#ff29d9\x94\x8c\x0fH2 electrolysis\x94\x8c\x07#ff29d9\x94\x8c\x03NH3\x94\x8c\x07#46caf0\x94\x8c\x07ammonia\x94\x8c\x07#46caf0\x94\x8c\rammonia store\x94\x8c\x07#00ace0\x94\x8c\x0fammonia cracker\x94\x8c\x07#87d0e6\x94\x8c\x0bHaber-Bosch\x94\x8c\x07#076987\x94\x8c\x08Sabatier\x94\x8c\x07#9850ad\x94\x8c\x0bmethanation\x94\x8c\x07#c44ce6\x94\x8c\x07methane\x94\x8c\x07#c44ce6\x94\x8c\x0fFischer-Tropsch\x94\x8c\x07#25c49a\x94\x8c\x06liquid\x94\x8c\x07#25c49a\x94\x8c\x15kerosene for aviation\x94\x8c\x07#a1ffe6\x94\x8c\x14naphtha for industry\x94\x8c\x07#57ebc4\x94\x8c\x14methanol-to-kerosene\x94\x8c\x07#C98468\x94\x8c\x1dmethanol-to-olefins/aromatics\x94\x8c\x07#FFA07A\x94\x8c\x18Methanol steam reforming\x94\x8c\x07#FFBF00\x94\x8c\x1bMethanol steam reforming CC\x94\x8c\x07#A2EA8A\x94\x8c\x0fmethanolisation\x94\x8c\x07#00FFBF\x94\x8c\x13biomass-to-methanol\x94\x8c\x07#EAD28A\x94\x8c\x16biomass-to-methanol CC\x94\x8c\x07#EADBAD\x94\x8c\x0eallam methanol\x94\x8c\x07#B98F76\x94\x8c\rCCGT methanol\x94\x8c\x07#B98F76\x94\x8c\x10CCGT methanol CC\x94\x8c\x07#B98F76\x94\x8c\rOCGT methanol\x94\x8c\x07#B98F76\x94\x8c\x08methanol\x94\x8c\x07#FF7B00\x94\x8c\x12methanol transport\x94\x8c\x07#FF7B00\x94\x8c\x11shipping methanol\x94\x8c\x07#468c8b\x94\x8c\x11industry methanol\x94\x8c\x07#468c8b\x94\x8c\x02CC\x94\x8c\x07#f29dae\x94\x8c\x03CCS\x94\x8c\x07#f29dae\x94\x8c\x11CO2 sequestration\x94\x8c\x07#f29dae\x94\x8c\x03DAC\x94\x8c\x07#ff5270\x94\x8c\nco2 stored\x94\x8c\x07#f2385a\x94\x8c\x0fco2 sequestered\x94\x8c\x07#f2682f\x94\x8c\x03co2\x94\x8c\x07#f29dae\x94\x8c\x08co2 vent\x94\x8c\x07#ffd4dc\x94\x8c\x0cCO2 pipeline\x94\x8c\x07#f5627f\x94\x8c\x14process emissions CC\x94\x8c\x07#000000\x94\x8c\x11process emissions\x94\x8c\x07#222222\x94\x8c\x1bprocess emissions to stored\x94\x8c\x07#444444\x94\x8c\x1fprocess emissions to atmosphere\x94\x8c\x07#888888\x94\x8c\roil emissions\x94\x8c\x07#aaaaaa\x94\x8c\x16shipping oil emissions\x94\x8c\x07#555555\x94\x8c\x1bshipping methanol emissions\x94\x8c\x07#666666\x94\x8c\x1cland transport oil emissions\x94\x8c\x07#777777\x94\x8c#agriculture machinery oil emissions\x94\x8c\x07#333333\x94\x8c\x08shipping\x94\x8c\x07#03a2ff\x94\x8c\rpower-to-heat\x94\x8c\x07#2fb537\x94\x8c\x0cpower-to-gas\x94\x8c\x07#c44ce6\x94\x8c\x0bpower-to-H2\x94\x8c\x07#ff29d9\x94\x8c\x0fpower-to-liquid\x94\x8c\x07#25c49a\x94\x8c\x11gas-to-power/heat\x94\x8c\x07#ee8340\x94\x8c\x05waste\x94\x8c\x07#e3d37d\x94\x8c\x05other\x94\x8c\x07#000000\x94\x8c\ngeothermal\x94\x8c\x07#ba91b1\x94\x8c\x0fgeothermal heat\x94\x8c\x07#ba91b1\x94\x8c\x18geothermal district heat\x94\x8c\x07#d19D00\x94\x8c geothermal organic rankine cycle\x94\x8c\x07#ffbf00\x94\x8c\x02AC\x94\x8c\x07#70af1d\x94\x8c\x05AC-AC\x94\x8c\x07#70af1d\x94\x8c\x07AC line\x94\x8c\x07#70af1d\x94\x8c\x05links\x94\x8c\x07#8a1caf\x94\x8c\nHVDC links\x94\x8c\x07#8a1caf\x94\x8c\x02DC\x94\x8c\x07#8a1caf\x94\x8c\x05DC-DC\x94\x8c\x07#8a1caf\x94\x8c\x07DC link\x94\x8c\x07#8a1caf\x94\x8c\x04load\x94\x8c\x07#dd2e23\x94\x8c\twaste CHP\x94\x8c\x07#e3d37d\x94\x8c\x0cwaste CHP CC\x94\x8c\x07#e3d3ff\x94\x8c\nHVC to air\x94\x8c\x01k\x94\x8c\timport H2\x94\x8c\x07#db8ccd\x94\x8c\nimport gas\x94\x8c\x07#f7a572\x94\x8c\nimport NH3\x94\x8c\x07#e2ed74\x94\x8c\nimport oil\x94\x8c\x07#93eda2\x94\x8c\x0fimport methanol\x94\x8c\x07#87d0e6\x94uuu\x8c\x04rule\x94\x8c\x17prepare_residual_inputs\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8c7/home/bjoern_local/git/pypsa-eur-evt/rules/MA/notebooks\x94ub.');del script;from snakemake.logging import logger;from snakemake.script import snakemake; logger.printshellcmds = False;import os; os.chdir(r'/home/bjoern_local/git/pypsa-eur-evt');
######## snakemake preamble end #########

In [31]:
# start coding here

In [32]:
# Imports and logging setup

import pandas as pd
import numpy as np
import logging
from pathlib import Path
import os

# Setup logging
logging.basicConfig(level=logging.INFO)

In [33]:
# Load config: Snakemake mode or standalone mode

try:
    config = snakemake.params.config
except NameError:
    import yaml
    with open("config/MA/config.128_wAT_entsoe_MA.yaml") as f:
        full_config = yaml.safe_load(f)
    config = full_config["residual_loads"]

In [34]:
# Resolve input file paths from config placeholders

def resolve_inputs(config):
    scenario = config["scenario"]
    input_dir = config["input_dir"]
    return {
        k: v.format(input_dir=input_dir, scenario=scenario)
        for k, v in config["inputs"].items()
    }

# Apply resolver
inputs = resolve_inputs(config)

In [35]:
# Create output directory if not existing (for standalone use)

out_path = Path(f"residual/{config['scenario']}/residual_inputs.parquet")
out_path.parent.mkdir(parents=True, exist_ok=True)

In [36]:
def read_and_standardize(file_path, source_name, tz="Europe/Vienna"):
    """
    Reads a semicolon-delimited CSV, parses datetime index, and standardizes the format.
    """
    logging.info(f"Reading {source_name} from {file_path}")

    df = pd.read_csv(file_path, sep=";", engine="python")

    # Detect datetime column
    datetime_column = None
    for col in df.columns:
        if "date" in col.lower() or "time" in col.lower() or "zeitpunkt" in col.lower():
            datetime_column = col
            break

    if datetime_column is None:
        raise ValueError(f"No datetime column found in {file_path}")

    df[datetime_column] = pd.to_datetime(df[datetime_column], dayfirst=True)
    df.set_index(datetime_column, inplace=True)

    # Ensure timezone-awareness
    df.index = df.index.tz_localize(tz, ambiguous='NaT', nonexistent='shift_forward')

    # Convert all columns to numeric
    df = df.apply(pd.to_numeric, errors='coerce')

    # Clean column names
    df.columns = [str(c).strip() for c in df.columns]

    df.sort_index(inplace=True)

    return df

In [37]:
# Load all input files

demand = read_and_standardize(inputs["nachfrage"], "demand")
pv = read_and_standardize(inputs["pv"], "pv")
wind = read_and_standardize(inputs["wind"], "wind")
biomass = read_and_standardize(inputs["biomasse"], "biomass")
hydro_large = read_and_standardize(inputs["gross_wasserkraft"], "hydro_large")
hydro_small = read_and_standardize(inputs["klein_wasserkraft"], "hydro_small")

INFO:root:Reading demand from data/MA/loads/NIP2030/Nachfrage.csv

INFO:root:Reading pv from data/MA/loads/NIP2030/PV.csv
INFO:root:Reading wind from data/MA/loads/NIP2030/Wind.csv
INFO:root:Reading biomass from data/MA/loads/NIP2030/biomasse.csv
INFO:root:Reading hydro_large from data/MA/loads/NIP2030/GrossWasserkraft.csv
INFO:root:Reading hydro_small from data/MA/loads/NIP2030/Kleinwasserkraft.csv

In [38]:
demand

,1002,1003,1004,1010,1012,1014,1015,1016,1017,1019,...,9050,9051,9052,9053,9054,9055,9062,9064,9065,9068
Zeitpunkt,,,,,,,,,,,,,,,,,,,,,
1930-01-01 00:00:00+01:00,0.162179,0.034319,0.028531,0.055433,0.036795,0.036002,0.023611,0.015696,0.016765,0.084959,...,0.008786,0.003341,0.002565,0.002089,0.002513,0.006579,0.015673,0.017296,0.002878,0.006357
1930-01-01 01:00:00+01:00,0.159844,0.033228,0.027213,0.053626,0.036231,0.034871,0.022357,0.014918,0.015582,0.080830,...,0.008519,0.003221,0.002465,0.002014,0.002405,0.006304,0.015406,0.016963,0.002796,0.006159
1930-01-01 02:00:00+01:00,0.160213,0.033680,0.027523,0.055124,0.036904,0.035923,0.022747,0.014981,0.015776,0.080642,...,0.008942,0.003508,0.002559,0.002053,0.002471,0.006507,0.015808,0.017295,0.002900,0.006479
1930-01-01 03:00:00+01:00,0.156922,0.032891,0.026962,0.052651,0.035917,0.034370,0.021935,0.014702,0.015293,0.076894,...,0.008442,0.003125,0.002439,0.002010,0.002392,0.006293,0.015125,0.016862,0.002787,0.006096
1930-01-01 04:00:00+01:00,0.156685,0.033496,0.027895,0.052804,0.036136,0.035180,0.022742,0.015196,0.016106,0.077663,...,0.008400,0.003028,0.002476,0.002066,0.002460,0.006406,0.015003,0.016896,0.002786,0.006076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2029-12-01 19:00:00+01:00,0.191233,0.057070,0.060453,0.086777,0.053162,0.075213,0.056336,0.031875,0.047454,0.155017,...,0.014912,0.006967,0.004837,0.003503,0.004812,0.011031,0.020281,0.022944,0.004537,0.009473
2029-12-01 20:00:00+01:00,0.181248,0.050895,0.052224,0.077187,0.048104,0.064870,0.047982,0.027782,0.039902,0.135134,...,0.013251,0.005902,0.004146,0.003043,0.004140,0.009747,0.018575,0.021099,0.004054,0.007994
2029-12-01 21:00:00+01:00,0.170437,0.045179,0.045307,0.067790,0.042928,0.054541,0.040631,0.024405,0.033773,0.116249,...,0.011644,0.004895,0.003500,0.002619,0.003515,0.008527,0.016977,0.019495,0.003600,0.006610
2029-12-01 22:00:00+01:00,0.162147,0.040180,0.038211,0.061010,0.039496,0.046581,0.033557,0.020760,0.026951,0.099464,...,0.010296,0.004068,0.002962,0.002263,0.002989,0.007492,0.015645,0.018148,0.003222,0.005455
2029-12-01 23:00:00+01:00,0.155531,0.036494,0.032808,0.055719,0.037102,0.040471,0.028063,0.017975,0.021578,0.085808,...,0.009321,0.003489,0.002591,0.002030,0.002599,0.006697,0.015221,0.017079,0.002967,0.004615

In [39]:
read_and_standardize("data/MA/loads/NIP2030/Nachfrage.csv", "Nachfrage").head()

INFO:root:Reading Nachfrage from data/MA/loads/NIP2030/Nachfrage.csv

,1002,1003,1004,1010,1012,1014,1015,1016,1017,1019,...,9050,9051,9052,9053,9054,9055,9062,9064,9065,9068
Zeitpunkt,,,,,,,,,,,,,,,,,,,,,
1930-01-01 00:00:00+01:00,0.162179,0.034319,0.028531,0.055433,0.036795,0.036002,0.023611,0.015696,0.016765,0.084959,...,0.008786,0.003341,0.002565,0.002089,0.002513,0.006579,0.015673,0.017296,0.002878,0.006357
1930-01-01 01:00:00+01:00,0.159844,0.033228,0.027213,0.053626,0.036231,0.034871,0.022357,0.014918,0.015582,0.080830,...,0.008519,0.003221,0.002465,0.002014,0.002405,0.006304,0.015406,0.016963,0.002796,0.006159
1930-01-01 02:00:00+01:00,0.160213,0.033680,0.027523,0.055124,0.036904,0.035923,0.022747,0.014981,0.015776,0.080642,...,0.008942,0.003508,0.002559,0.002053,0.002471,0.006507,0.015808,0.017295,0.002900,0.006479
1930-01-01 03:00:00+01:00,0.156922,0.032891,0.026962,0.052651,0.035917,0.034370,0.021935,0.014702,0.015293,0.076894,...,0.008442,0.003125,0.002439,0.002010,0.002392,0.006293,0.015125,0.016862,0.002787,0.006096
1930-01-01 04:00:00+01:00,0.156685,0.033496,0.027895,0.052804,0.036136,0.035180,0.022742,0.015196,0.016106,0.077663,...,0.008400,0.003028,0.002476,0.002066,0.002460,0.006406,0.015003,0.016896,0.002786,0.006076

In [41]:
# Ensure time index has unique values by grouping or dropping duplicates
def ensure_unique_index(df, method="mean"):
    return df.groupby(df.index).agg(method)

In [42]:
# Clean up any duplicate timestamps before reindexing
pv = ensure_unique_index(pv)
wind = ensure_unique_index(wind)
biomass = ensure_unique_index(biomass)
hydro_large = ensure_unique_index(hydro_large)
hydro_small = ensure_unique_index(hydro_small)

In [43]:
# Align all series to demand time index

common_index = demand.index
pv = pv.reindex(common_index).interpolate("time")
wind = wind.reindex(common_index).interpolate("time")
biomass = biomass.reindex(common_index).interpolate("time")
hydro_large = hydro_large.reindex(common_index).interpolate("time")
hydro_small = hydro_small.reindex(common_index).interpolate("time")

In [44]:
# Merge into single DataFrame

residual_inputs = pd.DataFrame(index=common_index)
residual_inputs["demand"] = demand.iloc[:, 0]
residual_inputs["pv"] = pv.iloc[:, 0]
residual_inputs["wind"] = wind.iloc[:, 0]
residual_inputs["biomass"] = biomass.iloc[:, 0]
residual_inputs["hydro_large"] = hydro_large.iloc[:, 0]
residual_inputs["hydro_small"] = hydro_small.iloc[:, 0]

# Fill NaNs just in case
residual_inputs.fillna(0, inplace=True)

In [45]:
# Save result to Parquet

residual_inputs.to_parquet(out_path)
logging.info(f"✅ Successfully wrote unified residual_inputs to {out_path}")

INFO:root:✅ Successfully wrote unified residual_inputs to residual/NIP2030/residual_inputs.parquet

In [46]:
# --------- OPTIONAL: DEBUG EXPORT TO CSV ----------
debug_csv_path = Path(f"residual/{config['scenario']}/residual_inputs.csv")
residual_inputs.to_csv(debug_csv_path, index=True)

logging.info("✅ Finished prepare_residual_inputs")

INFO:root:✅ Finished prepare_residual_inputs

In [47]:
residual_inputs

,demand,pv,wind,biomass,hydro_large,hydro_small
Zeitpunkt,,,,,,
1930-01-01 00:00:00+01:00,0.162179,0.0,0.005406,0.0624,0.101927,0.000092
1930-01-01 01:00:00+01:00,0.159844,0.0,0.006474,0.0624,0.101927,0.000092
1930-01-01 02:00:00+01:00,0.160213,0.0,0.006597,0.0624,0.100122,0.000092
1930-01-01 03:00:00+01:00,0.156922,0.0,0.006927,0.0624,0.100122,0.000092
1930-01-01 04:00:00+01:00,0.156685,0.0,0.007618,0.0624,0.100122,0.000092
...,...,...,...,...,...,...
2029-12-01 19:00:00+01:00,0.191233,0.0,0.007740,0.0624,0.104581,0.000107
2029-12-01 20:00:00+01:00,0.181248,0.0,0.006881,0.0624,0.104581,0.000107
2029-12-01 21:00:00+01:00,0.170437,0.0,0.007073,0.0624,0.104581,0.000107
2029-12-01 22:00:00+01:00,0.162147,0.0,0.007357,0.0624,0.104581,0.000107
2029-12-01 23:00:00+01:00,0.155531,0.0,0.006927,0.0624,0.104581,0.000107